all:
	cd base64; make
	cd cgi; make
	cd compress; make
	cd env; make
	cd gdbm;make
	cd mysql;make
	cd irc; make
	cd http; make
	cd toc; make
	cd pipe; make
	cd infostd; make

clean:
	cd base64; make clean
	cd cgi; make clean
	cd compress; make clean
	cd env; make clean
	cd gdbm;make clean
	cd mysql;make clean
	cd irc; make clean
	cd http; make clean
	cd toc; make clean
	cd pipe; make clean
	cd infostd; make clean

install:
	cd base64; make install
	cd cgi; make install
	cd compress; make install
	cd env; make install
	cd gdbm;make install
	cd mysql;make install
	cd irc; make install
	cd http; make install
	cd toc; make install
	cd pipe; make install
	cd infostd; make install
